### ISSUE TITLE
[Suggestion]: Remove compacting drawers quest

### ISSUE THREAD

**Issue by lunarlabs** [dr3ams/Life-in-the-village-3#102]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

In commit https://github.com/dr3ams/Life-in-the-village-3/commit/4f990309767e109f8cd2448bc14870395e44e2ea this line was added: `event.remove({output: 'storagedrawers:compacting_drawers_3'})` [(link to line)](https://github.com/dr3ams/Life-in-the-village-3/blob/main/kubejs/server_scripts/script.js#L49)

However, the "compacting drawers" quest is still in the quest tree.

**Comment by Crankonator** [comment]
The intention with the removal was actually that there was an issue that caused compacting drawers to crash the game upon use, however this issue should be fixed now and we simply forgot to readd the compacting drawers in our latest update

**Comment by lunarlabs** [comment]
Issue seems to be that Passive Skill Tree causes some conflict with Storage Drawers: https://github.com/Daripher/Passive-Skill-Tree/issues/189

**Comment by ScriptAero** [comment]
Guess he didnt properly fix said issue https://github.com/Daripher/Passive-Skill-Tree/issues/60#issuecomment-1832937250
I will have the quest removed by the next update.
