### ISSUE TITLE
[Suggestion]: Remove BetterCombat + Addons/Remove axe mechanics

### ISSUE THREAD

**Issue by Blueberrypie255** [dr3ams/Life-in-the-village-3#103]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

BetterCombat SUCKS! When I'm trying to chop down trees to get beehives, it seems to ALWAYS swing my axe and kill the bees instead of breaking the logs. When I'm in my MineColony adding and removing custom structures I make, my axe always wants to wander over and kill on of my colonists. It sucks. The axe feature should at least be removed.

**Comment by dr3ams** [comment]
Blacklisted axe in better combat. Should work in this case

**Comment by Blueberrypie255** [comment]
Thank you! Will those go into effect on the next update?
