### ISSUE TITLE
Not able to start server

### ISSUE THREAD

**Issue by lowkeyimloki1** [dr3ams/Life-in-the-village-3#105]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.19.2

### Describe your issue

Hi all,

Anyone having issues starting up a server? I am trying to run the bat file that comes from the server download but it runs a bunch of code quickly then says an error and ends with press any key to close. I can run any other server just fine. Any tips or changes I need to make for it to launch? I have java and jdk installed and updated and agreed to EULA. Thanks in advance.

### Additional Information

Here is the error that shows in the cmd :
[debug.log](https://github.com/dr3ams/Life-in-the-village-3/files/15152570/debug.log)

**Comment by Gunner76th** [comment]
Addressed already in discord. 

List of things that need to be changed for the server to run and to prevent file corruption:

1) remove Java 22, its not really supported by modded minecraft
2) install Java 17 https://adoptium.net/temurin/releases/?version=17&os=windows&arch=x64&package=jre
3) change where you are running your server from on your computer to something like c:\farm ser\
