### ISSUE TITLE
[Bug]: Yung's Extra's contains outdated structure files

### ISSUE THREAD

**Issue by GamingHQ** [dr3ams/Life-in-the-village-3#109]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

2.9

### Describe your issue

Yung's Extra contains outdated structure files, which can cause world gen lag. This mod also prefers to spawn inside villages or other monumental locations, breaking potential buildings and loot crates. ( Will come back later on this with a screenshot included, i just went stupid mode on shift deleting it lol )

### Steps to reproduce the issue

None. Randomly roaming on the map will cause the freezes during Worldgen. This causes significant drop/freeze moments when roaming.

### Additional Information

No crash logs. But, as stated before, i will come back with a beloved screenshot.

**Comment by Gunner76th** [comment]
Please provide logs files or citations from Yungs that supports this please. Without documentation to verify the statement, as well as a way to fix it, there is little we can do.

**Comment by GamingHQ** [comment]
> Please provide logs files or citations from Yungs that supports this please. Without documentation to verify the statement, as well as a way to fix it, there is little we can do.

Please, stay out of my bug reports if you are not a staff member.

**Comment by Gunner76th** [comment]
I am a staff member for Dreams and have been since about 2019. And even if I wasn't,  my previous statement is still true.

**Comment by GamingHQ** [comment]
Merge with issue #110 as its related to same situation.
