### ISSUE TITLE
Effective results in client crash if connecting to a server

### ISSUE THREAD

**Issue by r-lodahl** [dr3ams/Life-in-the-village-3#11]
**Describe the bug**
Clients crash if they connect to a server while Effective is installed. Effective is NOT presented on the server. The crash is not reproducable once effective is not present on the client.

**To Reproduce**
1. Run a server with LITV3 0.4 (of course without clientside mods)
2. Connect with a client with Litv3 0.4 installed (with client mods)
3. See error

**Expected behavior**
The client should connect to the server without a crash of the client.

**Log Files**
Sadly I restarted before copying the crash log. The vital exception however was:
java.lang.NullPointerException: Registry Object not present: effective_fg:droplet

**Comment by dr3ams** [comment]
Yeah, Effective will be deleted in the next update since it's mod's problem
https://github.com/bottomtextdanny/Effective-Forge-/issues/18

**Comment by dr3ams** [comment]
https://www.curseforge.com/minecraft/mc-mods/effective-forge/files/4017699
Ok it was updated and fixed
