### ISSUE TITLE
Jobs+ Introduction gets added on each Login

### ISSUE THREAD

**Issue by r-lodahl** [dr3ams/Life-in-the-village-3#12]
**Describe the bug**
On logging in with my character to my LITV3 server the "Jobs+ Introduction" gets added to my inventory.

**To Reproduce**
1. Login with a character to a server
2. Receive the book Jobs+ Introduction

**Expected behavior**
Jobs+ Introduction should only be added once per new character.

**Comment by dr3ams** [comment]
https://github.com/DAQEM/JobsPlus/issues/25
known issue, waiting for fix
