### ISSUE TITLE
[Bug]: mobs spawning issue

### ISSUE THREAD

**Issue by dr3ams** [dr3ams/Life-in-the-village-3#15]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

-

### Modpack version

-

### Describe your issue

Behavior:

> after a death the mob stop spawning, and after deconnection/connection the mob goes back.

### Additional Information

-

**Comment by dr3ams** [comment]
adaptive_performance_tweaks_ was deleted after reports. Waiting for more feedback.

**Comment by dr3ams** [comment]
![image](https://user-images.githubusercontent.com/7347489/196875707-0a55b749-78fe-49e6-98c5-4a490c2161c1.png)

Boss mob from Apotheosis. But we don't have Apotheois in litv 3 :(

**Comment by DoctorMage** [comment]
No other reports of mob spawning issues closing for now
