### ISSUE TITLE
[Suggestion]: LobsterJonn's mods

### ISSUE THREAD

**Issue by dr3ams** [dr3ams/Life-in-the-village-3#21]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

https://www.curseforge.com/minecraft/mc-mods/golemsarefriends
https://www.curseforge.com/minecraft/mc-mods/heyberryshutup

**Comment by CopperGiraffe** [comment]
I believe those have been added in 1.5
