### ISSUE TITLE
[Bug]: Simple Storage Network causing game crash

### ISSUE THREAD

**Issue by taggianto** [dr3ams/Life-in-the-village-3#23]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.4

### Describe your issue

Game is repeatedly crashing when trying to access a simple storage network connected to sophisticated storage barrels. 

Initially I was setting up the storage network inside a Nomad tent, so I thought maybe that was causing the issue. However, the crash continues to happen even after I moved the storage network to the overworld. I'm very early in the modpack, so the network only consists of 20 golden barrels. 

I did a clean install of the modpack and the issue continues to happen. It's not every single time you use the network, I've sometimes been able to use it for 10-15 minutes before accessing the network would cause a crash. 

### Steps to reproduce the issue

1. Set up a simple storage network with a root and crafting request table
2. Connect Sophisticated Storage barrels with link cables
3. Add items into the network
4. Exit out of the request table interface
5. Try and go back into the interface. (this is when the crash occurs)
6. Potentially may have something to do with holding an item in your hand when you right click the interface, but that may just be coincidental

### Additional Information

Error:
The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: mezz/jei/Internal

Exit code: -1

Crash report: https://pastebin.com/mWRZE5Cg

latest.log
Part 1: https://gist.github.com/taggianto/cae0c95e51df6b0b07430f84deb6c97f
Part 2: https://gist.github.com/taggianto/9f1aabb29234c274f0ee76c15e851f5b

**Comment by DoctorMage** [comment]
Issue with jei / ssn either try down grading jei version used or dont use jei feature of ssn

**Comment by DoctorMage** [comment]
No longer occurs in 1.7
