### ISSUE TITLE
[Suggestion]: Put this on a different mod website

### ISSUE THREAD

**Issue by chesse20** [dr3ams/Life-in-the-village-3#27]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Please put this on modrinth, ATLauncher, or Technic so that people can easily use it on MultiMC

**Comment by DoctorMage** [comment]
One option is downloading prism mc a fork of multimc downloading hte modpack on it launching it once then copying over the instance over to mmc instance folder.

Or mmc has its own method https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks

**Comment by dr3ams** [comment]
Not in priority for now. Maybe with LITV 4.
