### ISSUE TITLE
[Suggestion]: Increase builder speed

### ISSUE THREAD

**Issue by DoctorMage** [dr3ams/Life-in-the-village-3#28]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

![image](https://user-images.githubusercontent.com/85318453/211565717-2e4ae458-d2ce-4cc2-bc9f-fef3533914c8.png)
changed from 500 > 400 15 > 10

**Comment by chesse20** [comment]
is this in the server config somewhere i ran into the builder being slow myself

**Comment by DoctorMage** [comment]
yes world name

**Comment by chesse20** [comment]
> yes world name

what config file

**Comment by DoctorMage** [comment]
mine colonies

**Comment by DoctorMage** [comment]
Implemented in 1.7
for older worlds you have to manually apply it

Right click modpack icon
open folder
click on folder called saves go to your world find the folder called server config go inside their

for least amount of errors make a new world and just copy over the server config from the new world made in the newer modpack version

![image](https://user-images.githubusercontent.com/85318453/212933723-35acc102-2327-42b8-b5be-fdd660fe8c0e.png)

![image](https://user-images.githubusercontent.com/85318453/212933998-27c58afd-37ff-4af9-a0e4-f5ed60363f6f.png)

![image](https://user-images.githubusercontent.com/85318453/212934112-572aa296-541c-4c08-adab-f48205f53360.png)
