### ISSUE TITLE
[Bug]: Game crashes after world loaded.

### ISSUE THREAD

**Issue by bgrhnzcn** [dr3ams/Life-in-the-village-3#29]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Cursefogre

### Modpack version

1.6

### Describe your issue

The game crashes after 3 or 5 seconds of world loaded. I can see some blocks, then it crashes.

### Steps to reproduce the issue

Create a new world with cheats enabled and other settings are default.

### Additional Information

Exit code: -1073740940
[crash-2023-01-15_22.19.43-client.txt](https://github.com/dr3ams/Life-in-the-village-3/files/10421030/crash-2023-01-15_22.19.43-client.txt)
[2023-01-15-4.log.gz](https://github.com/dr3ams/Life-in-the-village-3/files/10421034/2023-01-15-4.log.gz)
[latest.log](https://github.com/dr3ams/Life-in-the-village-3/files/10421038/latest.log)

edit: The game crashes only when structures are generated. (I think the problem is villages, but I don't know exactly.)

**Comment by DoctorMage** [comment]
update to 1.7 and see if its still teh same
