### ISSUE TITLE
[Suggestion]: JVM overall perfomance tuning

### ISSUE THREAD

**Issue by manscm** [dr3ams/Life-in-the-village-3#32]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

The other day I found out how to make minecraft run a lot better.
I've tried to install different java virtual machine "Graal VM Enterprise 21.3" 
with these arguments"
`-Dgraal.LoopRotation=true -Dgraal.PartialUnroll=true -Dgraal.VectorizeSIMD=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1`
and perfomance has increased significantly, it's run buttery smooth.
It would be great if you share it somewhere to help others improve gaming experience :)

**Comment by DoctorMage** [comment]
Thanks for the suggestion normally jvm arguments are system depedant so they may not universally work

**Comment by dr3ams** [comment]
May be useful for someone, thanks for testing
