### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sweetashgamer** [dr3ams/Life-in-the-village-3#34]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.8

### Describe your issue

Chunks randomly disappear and refuse to load. Buildings become partially invisible and sometimes look very distorted. Doesn't happen every time I play but has happened three separate times now, causing me to have to close out and restart game to fix.

### Additional Information

https://imgur.com/a/zfJk1ys

**Comment by DoctorMage** [comment]
What gpu do you have?
