### ISSUE TITLE
[Bug]: Mod loading error(everythingiscopper)

### ISSUE THREAD

**Issue by jefetotal** [dr3ams/Life-in-the-village-3#35]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.8

### Describe your issue

Minecraft crashes while loading. This is my first time playing the modpack.

### Additional Information

[crash-2023-02-21_17.41.38-fml.txt](https://github.com/dr3ams/Life-in-the-village-3/files/10795725/crash-2023-02-21_17.41.38-fml.txt)

**Comment by DoctorMage** [comment]
just start again welcome to the future of modded its annoying but yeah happens every fresh modpack instances just need to launch it twice only happens first time launching
