### ISSUE TITLE
[Bug]: Unable to launch the modpack - some mods seem to be loaded incorrectly

### ISSUE THREAD

**Issue by elmuchacho367** [dr3ams/Life-in-the-village-3#37]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATLauncher

### Modpack version

1.8

### Describe your issue

Hi!
I've download your modpack, but it won't launch :(
The error message says that the problem is the mods "Chimes", "Drippy Loading Screen" and "Towns and Towers"
Googling the error didn't help, hope You will!

### Steps to reproduce the issue

1. load the modpack
2. launch the modpack

### Additional Information

[crash-2023-02-23_17.16.38-fml.txt](https://github.com/dr3ams/Life-in-the-village-3/files/10814403/crash-2023-02-23_17.16.38-fml.txt)
<img width="1186" alt="Снимок экрана 2023-02-23 в 17 17 15" src="https://user-images.githubusercontent.com/95048912/220933458-597cdab3-da4a-49a9-a5a9-780767628ea4.png">

**Comment by DoctorMage** [comment]
Did you try reinstalling and is this everytime launching the modpack?
