### ISSUE TITLE
[Bug]: Simple Storage Network crash with JEI 10.x

### ISSUE THREAD

**Issue by Demerso** [dr3ams/Life-in-the-village-3#39]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.9

### Describe your issue

JEI crashes when opening Simple Storage Network crafting terminal/remote with search sync activated.
This seems to be related to the newest version of JEI.

### Steps to reproduce the issue

If search sync is already activated:
  1. Log-in to a server
  2. Open inventory with crafting remote
  3. Game crashes

If search is not already activated (new world):
  1. Create world
  2. Place storage network
  3. Everything works fine
  4. Enable JEI sync
  5. Game crashes

### Additional Information

https://pastebin.com/gFpM3V6d

**Comment by Demerso** [comment]
Most likely the same as https://github.com/Lothrazar/Storage-Network/issues/476

**Comment by DoctorMage** [comment]
Make a new remote make sure you have the jei search turned off
![image](https://user-images.githubusercontent.com/85318453/223772811-2fc69a6f-4f2a-4f87-bf12-b958cb6e5267.png)

**Comment by Demerso** [comment]
> Make a new remote make sure you have the jei search turned off
> ![image](https://user-images.githubusercontent.com/85318453/223772811-2fc69a6f-4f2a-4f87-bf12-b958cb6e5267.png)
> 

Not ideal. But I guess that would be the easiest fix for now.
Pretty sure I'll accidentally activate it again.

**Comment by Demerso** [comment]
I made this mod release, which fixes the issue but forces the user to use R and U as JEI keybinds: https://github.com/Demerso/Storage-Network/releases/tag/SSN_JEI10-1

**Comment by DoctorMage** [comment]
Added warning in game
