### ISSUE TITLE
[Bug]: AlexsMobs:Crow taking too much ms to do their ticks

### ISSUE THREAD

**Issue by Eddenn** [dr3ams/Life-in-the-village-3#44]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

Life in the village 3 - 1.18.2 - 1.9

### Describe your issue

Hello,

I installed Life in the village 3 - 1.18.2 - 1.9 on my Minestrator server using their panel and launched the server.
Once connected i noticed some light freeze but really constantly. It apparently come from AlexsMobs Crow. (More details in Additional Information section) 

### Steps to reproduce the issue

- Install Life in the village 3 - 1.18.2 - 1.9 on a server
- Add Spark mod into server mods folder (1.9.11 (Forge 1.18.2)](https://www.curseforge.com/minecraft/mc-mods/spark/files/3824951)
- Maybe connect to the server and spawn Crow
- Run a /spark profiler --only-ticks-over 100 --timeout 30

### Additional Information

I'm not sure if the problem come from AlexsMobs alone or not, i just wanted to inform you.
I installed Life in the village 3 - 1.18.2 - 1.9 on my Minestrator server using their panel and launched the server.
Once connected i noticed some light freeze but really constantly, so opened a ticket on Minestrator to check if JVM were correctly defined or something like that.

But after some research we have run a Spark health check 
(http://spark.lucko.me/ny2dyzEFmI, you can expand "Server thread" to show the call tree) 
that showed that the problem was coming from `com.github.alexthe666.alexsmobs.entity.EntityCrow.m_8119_()` who took 868ms to do his tick.
(More precisely it the method that tool a long time is `com.github.alexthe666.alexsmobs.entity.ai.CrowAICircleCrops.isValidTarget()` )

The issues was "solved" by deactivating crow spawn in config/alexsmobs.toml (crowSpawnWeight = 0 and crowSpawnRolls = 0).

**Comment by dr3ams** [comment]
Thanks for the feedback and taking time to debug!
