### ISSUE TITLE
[Bug]: plague bringer enchant giving player bad effects

### ISSUE THREAD

**Issue by SHADOW-WOLF-FURRY** [dr3ams/Life-in-the-village-3#49]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

1.10

### Describe your issue

when using the plague bringer enchantment on any sword it causes the player to receive the bad effects and not the mob

### Steps to reproduce the issue

apply plague bringer to any sword and hit any mob

### Additional Information

enchantment should be applying bad effects to mobs hit by the player

**Comment by DoctorMage** [comment]
This is intended depeending on your corail aliement 
![image](https://user-images.githubusercontent.com/85318453/233711411-75b6f2b3-bc04-4e39-8213-1f6cebe832bf.png)
it will effect how certain corail enchants work
