### ISSUE TITLE
[Bug]: Cut copper walls missing

### ISSUE THREAD

**Issue by AdamDante85** [dr3ams/Life-in-the-village-3#52]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.11

### Describe your issue

Sandstone style stonemason lv 2 requires 4 cut copper walls but they do not exist nor can be crafted.

### Steps to reproduce the issue

1. Try crafting cut copper walls

### Additional Information

No crash, nothing to upload.

**Comment by DoctorMage** [comment]
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/79c3e0ff-8a1f-4589-be61-f43179fe3eaf)

**Comment by DoctorMage** [comment]
for refrence jei has different windows to show each option to craft an item 
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/39472256-7794-4b6a-bd40-2449807286dd)

**Comment by AdamDante85** [comment]
Yes cut copper can be crafted. Your screshoot is showing it. This item is about cut copper walls not a block. Cut copper can be crafted and is all fine, there is just no way to make a wall item out of it.

**Comment by DoctorMage** [comment]
screenshot the copper wall you mean

**Comment by DoctorMage** [comment]
found it

**Comment by DoctorMage** [comment]
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/ad33fbcd-8bd0-4c47-ac66-efd22c18493d)

**Comment by AdamDante85** [comment]
Oh. Ok I'll see if waxed works and let you know.

**Comment by AdamDante85** [comment]
Just tried but no luck. See below screens. 

1. Here I would expect to have the cut copper wall option but Domum Ornamentum does not see the block properly:
![Cut Copper](https://github.com/dr3ams/Life-in-the-village-3/assets/134238602/8e230881-074c-4b26-95e1-1c0e11541f8e)

2. I tried Waxed, Exposed and weathered but builder does not accept them:
![Other Cut Copper](https://github.com/dr3ams/Life-in-the-village-3/assets/134238602/7f8b2c95-a9d0-42f8-8f3b-189f514fe2a2)

It specifically asks for cut copper version and that does not exist. I have tried give command but even there the normal cut copper does not seem to be there - the others are but not this.

**Comment by DoctorMage** [comment]
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/9fccd153-3e1e-4051-ab0f-1dfe80ed2fea)
according to there discord known issue but no exact fix
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/472a1e47-c3cd-4f28-8035-6bd50784f33b)
same with just donum ornatum installed

**Comment by DoctorMage** [comment]
same on minecolonies discord both are pointing at eachother for the issue best to make an issue on donum page

**Comment by DoctorMage** [comment]
forgot to say but apparently in creative you can force add items or get them in gui of building

**Comment by dr3ams** [comment]
added repeatable quest for exchanging
