### ISSUE TITLE
[Bug]: 1.12 serverpack run.sh using incorrect nomenclature for forge version

### ISSUE THREAD

**Issue by koolaidxk1d** [dr3ams/Life-in-the-village-3#53]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

N/A

### Modpack version

1.12 SERVER PACK

### Describe your issue

Inside the 1.12 server pack, the included run.sh does not include the proper path to forge. The path should say 40.2.9, not 40.2.0. I can see that the run.bat was updated to include this, but the run.sh was not. Probably a minor oversight.

The server will fail to start using the script without modifying it, and I think some people will not know how to fix that themselves.

### Additional Information

N/A

**Comment by shaedy180** [comment]
I had and still have the same problem. My server won't start, even though I adjusted the run.sh file to reflect the full path - "/opt/java17/bin/java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.2-40.2.9/unix_args.txt "$@""
