### ISSUE TITLE
[Bug]: crash

### ISSUE THREAD

**Issue by AhmedAbdElNaSsSer** [dr3ams/Life-in-the-village-3#54]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curse forge and main launcher 

### Modpack version

1.18.2

### Describe your issue

A bug happened! when i'm trying to open the game every time this crash happen
![image_2023-06-23_175504054](https://github.com/dr3ams/Life-in-the-village-3/assets/97300429/b15a79e0-75c8-4ae4-ada0-a123335aaf19)

### Additional Information

[latest.log](https://github.com/dr3ams/Life-in-the-village-3/files/11849624/latest.log)

**Comment by DoctorMage** [comment]
what cpu and gpu does your pc have

**Comment by AhmedAbdElNaSsSer** [comment]
core i5 11gen rtx3060

**Comment by AhmedAbdElNaSsSer** [comment]
> what cpu and gpu does your pc have


core i5 11gen rtx3060

**Comment by DoctorMage** [comment]
is this the first time playing and running the modpack if so try deleting and reinstalling it

**Comment by AhmedAbdElNaSsSer** [comment]
> is this the first time playing and running the modpack if so try deleting and reinstalling it
if you mean this modpack yes first time and didn't work in first start and i reinstalled it many times and download "life of the village 2" and still same error crashing without start but i'm playing another modpacks and it's ok i don't know what's wrong

**Comment by AhmedAbdElNaSsSer** [comment]
> is this the first time playing and running the modpack if so try deleting and reinstalling it

> is this the first time playing and running the modpack if so try deleting and reinstalling it
if you mean this modpack yes first time and didn't work in first start and i reinstalled it many times and download "life of the village 2" and still same error crashing without start but i'm playing another modpacks and it's ok i don't know what's wrong

**Comment by AhmedAbdElNaSsSer** [comment]
> is this the first time playing and running the modpack if so try deleting and reinstalling it

if you mean this modpack yes first time and didn't work in first start and i reinstalled it many times and download "life of the village 2" and still same error crashing without start but i'm playing another modpacks and it's ok i don't know what's wrong

**Comment by DoctorMage** [comment]
try atlauncher and see if the modpack works on it https://atlauncher.com/downloads

**Comment by AhmedAbdElNaSsSer** [comment]
> is this the first time playing and running the modpack if so try deleting and reinstalling it
what should i do any help ?

**Comment by AhmedAbdElNaSsSer** [comment]
> try atlauncher and see if the modpack works on it https://atlauncher.com/downloads

yeah i tried it and tried SKLauncher and nothing happen ..

**Comment by AhmedAbdElNaSsSer** [comment]
> try atlauncher and see if the modpack works on it https://atlauncher.com/downloads

so any help !!

**Comment by AhmedAbdElNaSsSer** [comment]
in atlauncher modpack is opened but why in curseforge this error comes ?

**Comment by DoctorMage** [comment]
curseforge has issues sometimes 

normally changing the default file path should fix it 
but if atlauncher is working thats an option to use

**Comment by AhmedAbdElNaSsSer** [comment]
> curseforge has issues sometimes
> 
> normally changing the default file path should fix it but if atlauncher is working thats an option to use

ok for now i will use atlauncher thx for helping .. but i have another question i want to make a server in RAD2 and joining to server an error appears ( incompletable fml modded server minecraft )  what should i do

**Comment by DoctorMage** [comment]
take it to rad github please

**Comment by DoctorMage** [comment]
https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues

**Comment by DoctorMage** [comment]
most likely your starting the server with minecraft_server.1.16.5.jar do not do that use the launchserve.bat if you ever started it with that jar you need a new serverpack
