### ISSUE TITLE
[Bug]: The game crashed whilst unexpected error Error: java.lang.NoClassDefFoundError: mezz/jei/Internal

### ISSUE THREAD

**Issue by JdotMo** [dr3ams/Life-in-the-village-3#56]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

1.12

### Describe your issue

A bug happened!

Turning on JEI Searching in a simple storage network stroage requestt table, storage remote, or crafting remote causes the game to crash and keep crashing until you craft another one or pick up and replace the network root

### Steps to reproduce the issue

1. Open crafting remote
2. turn on JEI Search to enabled 
3. close crafting remote UI and reopen
4. Game will crash
5. Will keep crashing till you craft another one

### Additional Information

[crash-2023-06-24_10.27.17-client.txt](https://github.com/dr3ams/Life-in-the-village-3/files/11857814/crash-2023-06-24_10.27.17-client.txt)

**Comment by DoctorMage** [comment]
Make a new remote and do not enable jei feature on it
