### ISSUE TITLE
[Bug]: Nether out of bounds issue

### ISSUE THREAD

**Issue by rewenx** [dr3ams/Life-in-the-village-3#58]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Prism (MULTIPLAYER SERVER)

### Modpack version

1.3 

### Describe your issue

We're getting sporadic crashes in the nether dimension only on multiplayer. When players try to load a certain area in the nether, the server crashes. We reboot and its fine, then the player logs back in and crashes the server again. 

We're not limiting the world size in any way, I don't know why we'd be getting an "out of bounds" message. 

To fix it we need to tp the affected player out of the nether using commands before their client attempts to load the area. We've been having this issues since the start of the server and have been avoiding the nether.  I also tried deleting region files in the nether with no luck.

I searched the entire discord for this error, and a few people have also had this problem, but no resolution was offered in those posts. I believe one of the mods adding world gen in the nether is causing a problem, though I cannot identify which one.

We've since added a few mods, but since its been happening all along we don't attribute them to this issue.

### Steps to reproduce the issue

Can reliably reproduce this crash when a player tries to load an area in the nether.

### Additional Information

[crash-2023-07-22_18.40.23-server.txt](https://github.com/dr3ams/Life-in-the-village-3/files/12137115/crash-2023-07-22_18.40.23-server.txt)

**Comment by rewenx** [comment]
Doctor Mage let me know this is possibly related to this issue with bygone nether. https://github.com/izofar/bygone-nether/issues/29

**Comment by izofar** [comment]
This is an issue with my mod, you can close on your end.
