### ISSUE TITLE
[Bug][2.0]: Broken world generation

### ISSUE THREAD

**Issue by romaust** [dr3ams/Life-in-the-village-3#61]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

MultiMC

### Modpack version

2.0

### Describe your issue

Broken world generation in **Large Biome** world type. In normal world type the problem didn't come up

### Steps to reproduce the issue

1. Create world with **Large Biome** world type
2. Move in somewere for long time
3. Leave the world and launch it again
4. Move in the sayme direction a bit
5. Watch another world generation

### Additional Information

[latest.log](https://gist.github.com/romaust/db8d99580fdccc3ea5c9a1657976f430)
[debug.log](https://gist.github.com/romaust/a013a28fe998d28bb96900b44a82b97e)
[screenshots](https://imgur.com/a/cs9eruz)

**Comment by dr3ams** [comment]
With the current world gen mod(Tectonic) it's possible to enable large biomes only in configs

**configs -> tectonic.toml**
```
["Tectonic Mod Config"]
	#Put "true" if you want large biomes to be enabled. Defaults to "false".
	"Large Biomes Enabled" = false
```
