### ISSUE TITLE
[Bug]: Axes not breaking wood-related objects faster than bare hand

### ISSUE THREAD

**Issue by dattmse140171** [dr3ams/Life-in-the-village-3#62]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

TLauncher

### Modpack version

LITV3-1.19.2-2.0

### Describe your issue

Every axes in the game do not speed up the breaking of any wooden blocks, the breaking speed stays equivalent to breaking using a bare hand. 
Furthermore, I notice that when hovering the crosshair over any wooden blocks, there is no axe icon appears on the right corner of the indicator like hovering over other blocks (as in the second image, the cobblestone when hovering has the pickaxe symbol in the indicator at the top middle screen).

### Steps to reproduce the issue

1. Use any axe, either wood, stone, iron, or even netherite, to break any wood-based blocks

### Additional Information

Missing tool (axe) indicator for wood-based-blocks
https://imgur.com/a/OjwQAQG

Speed comparison:
https://imgur.com/a/wnPRQS7

**Comment by xXDeonoXx** [comment]
i'm having the same issue, what am i doing wrong ?

**Comment by DoctorMage** [comment]
Something is wrong. The mod Floor Mats is breaking the axe tag.  You can replace the mod in the mod folder with the updated version released today. https://www.curseforge.com/minecraft/mc-mods/floor-mats/files/4673069
Assuming you are using the 1.19.2 version.
