### ISSUE TITLE
[Bug]: LitV3 2.0 - Diamond 

### ISSUE THREAD

**Issue by Dragoon209** [dr3ams/Life-in-the-village-3#63]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

GD Launcher

### Modpack version

2.0

### Describe your issue

When attempting to redeem the diamond coin epic loot box, the coin is consumed but the loot box does not spawn when clicked.  The other coin redemption loot boxes work correctly. 

The quest in question is in $ - COIN SHOP - $  > 2nd Row, 4th quest over.  Purple chest icon.  It looks like the reward ID is 3C25C0FEAF1FD585

### Steps to reproduce the issue

1. Acquire a blue diamond coin
2. Enter the quest menu, and navigate to the COIN SHOP
3. attempt to redeem the coin by clicking the purple chest.  The quest will complete when submitting the blue coin, but the reward does not drop when clicked.

### Additional Information

No additional info appears to be present in the console or the latest.log

**Comment by dr3ams** [comment]
Fixed the issue on my end by simply remaking the quest. Will be up in the next update
