### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SonicNico** [dr3ams/Life-in-the-village-3#65]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.1

### Describe your issue

Rotating Minecolonies building previews only shifts the preview instead of actually rotating them, making it near impossible to do anything with the mod.

### Steps to reproduce the issue

1. Select building with build tool. 2. Click either rotate button on the UI. 3. Notice the lack of rotation, and the shifting of building instead.

### Additional Information

No crashes, just very frustrating as it was working before updating to 2.1 from 2.0. The hosting service we're using doesn't allow us to go back to 2.0 so we're stuck.

**Comment by DoctorMage** [comment]
Known issue with structurize mod only way to fix it is by updating structurize to its latest version until dreams updates the modpack
