### ISSUE TITLE
[Bug]: Villagers unable to plant or harvest crops due to Open Parties and Claims default settings

### ISSUE THREAD

**Issue by cambakr** [dr3ams/Life-in-the-village-3#66]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.1

### Describe your issue

Tried to make a automatic villager breeder and I claimed and forceloaded the chunk. Villagers wouldn't plant or harvest from their farm due to the default setting of claims.protection.exceptionGroups.entity.blockAccess.Villagers in my player-config. The default is 0 and if I understand correctly the correct option for fixing this should be 3 since villagers aren't owned.

From the unmodified "[world directory]/serverconfig/openpartiesandclaims-default-player-config.toml" file:

```
[playerConfig.claims.protection.exceptionGroups.entity.blockAccess]
    #When enabled, claimed chunk protection makes an exception for block access by the following entities: minecraft:villager. If the block protection is based on the mob griefing rule check, then the claimed neighbor chunks must also allow the block access.
    #
    #1) Party - players or entities owned by players in the same party as you.
    #2) Allies - players or entities owned by players in parties that are allied by yours.
    #3) Every - all players/entities.
    Villagers = 0
```

Expected behavior would be that villagers would be able to farm crops by default. This may also lead to issues with rules pertaining to sheep and them being able to eat a grass block to regenerate wool (playerConfig.claims.protection.exceptionGroups.entity.break). 

Hopefully this can be modified to be a default and isn't something that can only be modified post generation.

### Additional Information

N/A

**Comment by DoctorMage** [comment]
changed in https://github.com/dr3ams/Life-in-the-village-3/commit/31bde5cb21bec8d4ace4ac92d0dd153746dd6810
