### ISSUE TITLE
[Bug]: Server Crashing due to (maybe) pirate raider event spawn?

### ISSUE THREAD

**Issue by AlphaSutoraiku** [dr3ams/Life-in-the-village-3#67]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

2.1

### Describe your issue

Our server we are playing on crashes semi-regularly. I have a suspicion that it is related to MineColonies and maybe somehow the/a pirate raider spawn event, as I and others have sometimes seen a chat message reporting something about pirate raiders very shortly before the server crashing.

### Additional Information

Here are the latest 4 crash reports: 

[crash-2023-08-15_11.55.17-server.txt](https://github.com/dr3ams/Life-in-the-village-3/files/12343403/crash-2023-08-15_11.55.17-server.txt)
[crash-2023-08-15_12.32.51-server.txt](https://github.com/dr3ams/Life-in-the-village-3/files/12343405/crash-2023-08-15_12.32.51-server.txt)
[crash-2023-08-14_23.37.59-server.txt](https://github.com/dr3ams/Life-in-the-village-3/files/12343406/crash-2023-08-14_23.37.59-server.txt)
[crash-2023-08-15_00.06.44-server.txt](https://github.com/dr3ams/Life-in-the-village-3/files/12343407/crash-2023-08-15_00.06.44-server.txt)

**Comment by DoctorMage** [comment]
escription: Exception in server tick loop

java.lang.NoSuchMethodError: 'void com.ldtteam.structurize.management.Manager.addToQueue(com.ldtteam.structurize.util.TickedWorldOperation)'

seems to be something to do with structurize

make a backup of the world and update the mod

**Comment by cambakr** [comment]
After refreshing crashes have continued.
[crash-2023-08-18_00.29.36-server.txt](https://github.com/dr3ams/Life-in-the-village-3/files/12375271/crash-2023-08-18_00.29.36-server.txt)

**Comment by DoctorMage** [comment]
is it the same after updating structurize?

**Comment by cambakr** [comment]
I manually updated Structurize to 1.0.629 and am still experiencing crashes. One was a general Structurize related crash and the other was specific to the pirate ship again. Pirate ship crash log attached.
[crash-2023-08-22_22.33.44-server.txt](https://github.com/dr3ams/Life-in-the-village-3/files/12413474/crash-2023-08-22_22.33.44-server.txt)

**Comment by DoctorMage** [comment]
https://github.com/ldtteam/Structurize/issues/600

**Comment by cambakr** [comment]
After updating Structurize to the 1.0.630 release, we have had a pirate ship spawn without a crash.
