### ISSUE TITLE
[Bug]: Aquaculture 2

### ISSUE THREAD

**Issue by Kaiiiiiiiiii** [dr3ams/Life-in-the-village-3#68]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

LITV3-1.19.2-2.1

### Describe your issue

I am running a Minecraft Server with the modpack "life in the village 3 (LITV3-1.19.2-2.1)".

I have a problem with the aquaculture 2 mod, i cant catch any modrelated fish. I see the items in NEI and i can also craft them and use the rods, but i only catch vanilla fish or croptopia fish.

Version: Aquaculture-1.19.2-2.4.8

- i tested it for 2h and got 1000 non related fish
- i used different rods from the aquaculture mod
- I tested the aquaculture 2 mod by itself and a secound time with croptopia. In both instances it was working fine

I also checked the server folders:![Screenshot_1](https://github.com/dr3ams/Life-in-the-village-3/assets/57196684/55244b06-0db8-436c-9686-0ecace3e065c)

### Steps to reproduce the issue

1. open the game on version 2.0 or newer.
2. start a new world.
3. try to catch any aquaculture related fish.

### Additional Information

It's not crashing

**Comment by DoctorMage** [comment]
fixed in https://github.com/dr3ams/Life-in-the-village-3/commit/d0b4849697006aab5ccb352c9b7cc1c0ab24185a
