### ISSUE TITLE
[Bug]: Supplementaries Lantern Tweaks causing fires with Minecolonies builders

### ISSUE THREAD

**Issue by cambakr** [dr3ams/Life-in-the-village-3#70]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.1

### Describe your issue

Supplementaries applies tweaks to lanterns that cause them to fall and start a fire if the block they are attached to is broken. This has a setting in the Supplementaries config and is enabled by default. Having it enabled can result in fires breaking out as Minecolonies builders perform upgrades to buildings. 

I recommend a default config that disables the tweaks outright or uses the no fire option in the Supplementaries config.

I specifically encountered this issues when upgrading the university from level 3 to 4 using the Colonial style.

### Additional Information

N/A

**Comment by DoctorMage** [comment]
changed in [f2db4ca](https://github.com/dr3ams/Life-in-the-village-3/commit/f2db4ca2219daf3a3861d65905d4e2c06bb14439)
