### ISSUE TITLE
[Bug]: Lootr mod does not work properly in multiplayer world

### ISSUE THREAD

**Issue by TchoKnut** [dr3ams/Life-in-the-village-3#72]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.2

### Describe your issue

Me and my friend have a multiplayer world with the latest version of the modpack. (2.2)
Now we went exploring and saw the chests from the Lootr mod. However, these were completely empty, which couldn't be true since we hadn't been in this area before. So we continued walking and found more chests on our way, some of which were empty but occasionally 1-2 that were filled but sometimes only for one of us.
By the way, if we opened a chest that was empty and waited about 3 minutes, it would be displayed again as if it still contained loot.

### Additional Information

-

**Comment by TchoKnut** [comment]
Why did you add the tag "Unable to fix"? There must be a reason why it worked in previous versions of your modpack and no longer works. Is there absolutely nothing you can do? It could also simply be that Lootr is no longer compatible with another mod pack that you have recently added.

**Comment by DoctorMage** [comment]
Right

get the world seed

coordinates and confirm that the chest generate loot in one modpack version 2.1 and then see iff its the same in 2.2

the reason cant fix was put was due to it being an issue with lootr rarely it can generate chest with no loot depending on the structure

if you can confirm it down to a specific structure then it can be reported to lootr team to see if it can be fixed on there end

**Comment by DoctorMage** [comment]
https://github.com/noobanidus/Lootr/issues/178
