### ISSUE TITLE
[Bug]: exit code 1 when clicking play in the launcher

### ISSUE THREAD

**Issue by theachup** [dr3ams/Life-in-the-village-3#73]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

2.2

### Describe your issue

when i click play in the minecraft launcher, it loads for a couple of seconds, it closes the launcher and then shows exit code 1.

### Steps to reproduce the issue

not relevant

### Additional Information

[latest.log](https://github.com/dr3ams/Life-in-the-village-3/files/12706499/latest.log)

**Comment by TchoKnut** [comment]
Did it happen before or did it happen for the first time with this modpack?

**Comment by theachup** [comment]
it happened the first time (sorry for the very late response)

**Comment by DoctorMage** [comment]
right click on the icon
open folder
click here
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/595a36bb-27f2-4f35-acf4-f864396fec40)
then delete the actual modpack folder
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/c8a21c51-0153-4cba-b4e9-aa05f492325f)
install again

**Comment by theachup** [comment]
thanks for the response, but this sadly doesnt work.

**Comment by DoctorMage** [comment]
change the default filepath https://imgur.com/a/df1DdFB
