### ISSUE TITLE
[Bug]: Odd loots in dungeon (Tetra heavily affected)

### ISSUE THREAD

**Issue by KintonHiryuu** [dr3ams/Life-in-the-village-3#75]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

2.2

### Describe your issue

We were looking for Tetra's scrolls for hours, many chests were opened, in single player, multiplayer, survival, creative and so on both with and without Luck effect, each times in chests that can contain those scrolls (Nether Fortress/Dungeons - checked with jd-gui in the mod's code + on the mod's discord server)

So we began testing by removing other mods, and found out it was a compatibilty issue with IDAS, replacing the drop tables and filling the chests with flint and steel, or stuff with <5% durability (check the end fortress stuff you will laugh)

After removing IDAS (and dependents) we immediately got Tetra's scrolls in the chests and the loot in them was much more interesting

Here's the list of mods we disabled to get it working properly :
- IDAS Forge
- Integrated API
- Yungs API
- Yungs Extra
- Yungs Better Ocran Moments
- Yungs Better Desert Temples
- Yungs Better Nether Fortresses
- Yungs Better With Huts
- Yungs Better Strongholds
- Yungs Better Mineshafts
- Yungs Better Dungeons
- Travelers Titles
- Paxi

### Steps to reproduce the issue

1 - Generate new map (singleplayer or multiplayer)
2 - open dungeons chests or nether fortress for Tetra's Items, or End Cities ones for fun
3 - Deletes said mods
4- Redo

### Additional Information

Please note : the scrolls we are speaking here are quest items, other items does not spawn but we didnt notice them

Tetra's Discord server : https://discord.gg/MyjK4Fx

List of mods files :
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/60929021/4ee135ec-2fcc-454e-b535-bcd9ac56393b)

End Cities chests :
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/60929021/5f8c9b93-1fac-4357-a555-78f5b979e89d)
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/60929021/7c7d22c9-10b8-481a-91dc-9d0111e7d998)

Nether Fortess chests (should be able to contain Tetra's Items)
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/60929021/fef20c8e-2ee2-4a13-bb5d-0b9485748681)
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/60929021/739bad7d-22c2-493b-af71-ebfe4d70ff7b)

**Comment by DoctorMage** [comment]
If you can recreate this with just idas and tetra

report it to both mods respective githubs please

**Comment by DoctorMage** [comment]
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/0049f04b-ce2d-4500-953b-3d9c0d053cff)
seed -6358536587401535074
singleplayer

just idas (and its depedents)
as well as tetra

**Comment by DoctorMage** [comment]
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/79ed5920-f640-4137-8d81-0734c37f47ee)

Life in the village 3\config\paxi\datapacks
1-19-1-19-3-loot-and-structures-amount-reducer.zip

most likely this

**Comment by Linguardium** [comment]
This also creates issues with Corail's Tombstone drops breaking its loot table injection system (no drops from undead, mod is nearly impossible to do) and is an issue on 2.1 as well with that datapack in paxi's folder.  Without the datapack, Corail's tombstone generates the world/tombstone/loottables/ folder with the loot entries in it. with the datapack, it does not do this and mod drops do not occur from mobs.

**Comment by KintonHiryuu** [comment]
So if i understand what you say : if we disable the datapack, we still get all the mod's benefit while getting rid of the bugs, and this MAY create no issues above ?

i'll try this on my friend's server and will tell you if we see something odd, thanks

**Comment by Linguardium** [comment]
https://www.planetminecraft.com/data-pack/reduced-loot-and-structures-amount/ is the datapack that you would be removing. it appears to replace a large portion of vanilla loot tables...but load order is defined, meaning it is likely to just completely overwrite several loot tables after they have been modified/added to. generally it may work if it is in the datapack list and is loaded before all mods load, but otherwise this type of modification is a VERY bad idea

**Comment by KintonHiryuu** [comment]
i did disable this pack since yesterday, and the loots seem much more correct, and we were able to go forward in tetra as we wanted so much, hope you'll get a fix for everyone

**Comment by KintonHiryuu** [comment]
just looked at the ancient cities, the ancient tree sapling dont spawn and the coral's tombstone scrolls neither
stuff we loot have one tenth of their life

disable the datapack everything goes back to normal, hope you dont want to build with white log

**Comment by Linguardium** [comment]
I would suggest removing the file completely in the config/paxi folder to prevent it from even being loaded. server restarts wont cause it to redownload itself
