### ISSUE TITLE
[Bug]: Missing trades with villager (Tetra heavily affected)

### ISSUE THREAD

**Issue by KintonHiryuu** [dr3ams/Life-in-the-village-3#76]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

2.2

### Describe your issue

Still in our quest for Tetra's Scrolls (#75) we took a look at the villager's trades, especially the fletcher's ones
Fletcher may have up to 3 scrolls to trade when level max (master) (source : Tetra's discord)

Seeing the money vilagers traded, we directly removed the mod [numismatic-overhaul](https://www.curseforge.com/minecraft/mc-mods/numismatic-overhaul) and got a villager that traded all 3 scrolls at once

When re-adding it, no new villagers will get one of those trades

We also notice some trades that are in our opinion really over powered

### Steps to reproduce the issue

1. Create a world
2. "create" a Fletcher villager and make it Master level
3. Observe trades - no Tetra's scrolls
4. Remove said mod from folders
5. re create a Fletcher max level
6. Observe trades - you got scrolls

### Additional Information

Tetra's discord server : https://discord.gg/MyjK4Fx

Curseforge mod : https://www.curseforge.com/minecraft/mc-mods/numismatic-overhaul

Numismatic villager trades : 
```{maxUses: 12, buyB: {id: "minecraft:air", Count: 0, tag: {Charged: 0b}}, buy: {id: "numismaticoverhaul:silver_coin", Count: 1}, sell: {id: "minecraft:arrow", Count: 16}, xp: 5, uses: 0, Reputation: 8, priceMultiplier: 0.05f, specialPrice: 0, demand: -4776, rewardExp: 1b}, {maxUses: 8, buyB: {id: "minecraft:air", Count: 0, tag: {Charged: 0b}}, buy: {id: "numismaticoverhaul:silver_coin", Count: 20}, sell: {id: "minecraft:bow", Count: 1, tag: {Damage: 0}}, xp: 8, uses: 0, Reputation: 8, priceMultiplier: 0.05f, specialPrice: 0, demand: -3184, rewardExp: 1b}, {maxUses: 12, buyB: {id: "minecraft:air", Count: 0, tag: {Charged: 0b}}, buy: {id: "minecraft:string", Count: 16}, sell: {id: "numismaticoverhaul:bronze_coin", Count: 80}, xp: 5, uses: 0, Reputation: 8, priceMultiplier: 0.05f, specialPrice: 0, demand: -4560, rewardExp: 1b}, {maxUses: 4, buyB: {id: "minecraft:air", Count: 0, tag: {Charged: 0b}}, buy: {id: "numismaticoverhaul:silver_coin", Count: 12}, sell: {id: "minecraft:crossbow", Count: 1, tag: {Damage: 0}}, xp: 8, uses: 0, Reputation: 8, priceMultiplier: 0.05f, specialPrice: 0, demand: -1520, rewardExp: 1b}, {maxUses: 12, buyB: {id: "minecraft:air", Count: 0, tag: {Charged: 0b}}, buy: {id: "numismaticoverhaul:silver_coin", Count: 15}, sell: {id: "minecraft:feather", Count: 15}, xp: 5, uses: 0, Reputation: 8, priceMultiplier: 0.05f, specialPrice: 0, demand: -4524, rewardExp: 1b}, {maxUses: 2, buyB: {id: "minecraft:bow", Count: 1, tag: {Damage: 0}}, buy: {id: "numismaticoverhaul:silver_coin", Count: 20}, sell: {id: "minecraft:bow", Count: 1, tag: {Damage: 0, Enchantments: [{lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:flame"}]}}, xp: 10, uses: 0, Reputation: 8, priceMultiplier: 0.05f, specialPrice: 0, demand: -754, rewardExp: 1b}, {maxUses: 2, buyB: {id: "minecraft:crossbow", Count: 1, tag: {Damage: 0}}, buy: {id: "numismaticoverhaul:silver_coin", Count: 7}, sell: {id: "minecraft:crossbow", Count: 1, tag: {Damage: 0, Enchantments: [{lvl: 1s, id: "minecraft:quick_charge"}]}}```

![image](https://github.com/dr3ams/Life-in-the-village-3/assets/60929021/89816e51-033a-4189-847d-986914cc0fb7)

![image](https://github.com/dr3ams/Life-in-the-village-3/assets/60929021/f8edd870-15ad-4a34-b3bb-0500f97c1937)

**Comment by DoctorMage** [comment]
https://github.com/wisp-forest/numismatic-overhaul/issues/105
