### ISSUE TITLE
[Bug]: Flywheel has failed to load correctly

### ISSUE THREAD

**Issue by mishaphiliaq** [dr3ams/Life-in-the-village-3#77]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.2

### Describe your issue

So, i installed this modpack today and for several hours i tried to fix the issue.
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/145903103/af3c250f-1ebd-4b76-b79e-faa2dd88482a)
It just starts like this and that's all.
Modpack reinstall didn't help
Create reinstall didn't help
Installing Flywheel didn't help

### Steps to reproduce the issue

1. Install Modpack
2. Start the game
3. Done.

### Additional Information

[crash-2023-09-24_13.13.19-fml.txt](https://github.com/dr3ams/Life-in-the-village-3/files/12708251/crash-2023-09-24_13.13.19-fml.txt)

**Comment by DoctorMage** [comment]
cpu: Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
gpu: NVIDIA GeForce 920MX
how much total ram does your pc have
drivers last updated a year ago try updating your gpu drivers

**Comment by mishaphiliaq** [comment]
> cpu: Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz gpu: NVIDIA GeForce 920MX how much total ram does your pc have drivers last updated a year ago try updating your gpu drivers

12 gb of ram
i will try updating my drivers, thanks

**Comment by DoctorMage** [comment]
also set the ram allocation to
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/e09d6e3e-b081-494c-b8a7-6ade63619689)


8192 or 6144

**Comment by mishaphiliaq** [comment]
> also set the ram allocation to ![image](https://user-images.githubusercontent.com/85318453/270188418-e09d6e3e-b081-494c-b8a7-6ade63619689.png)
> 
> 8192 or 6144

did not help.
I updated my drivers and that didn't do anything.
I allocated 8192 mb of memory for modpack
Tried even updating Create, but that didn't do much as well.

**Comment by DoctorMage** [comment]
try changing the default path curseforge uses sometimes the default one can have issues with how windows is

https://imgur.com/a/df1DdFB
