### ISSUE TITLE
Game Crashed Message on Startup 

### ISSUE THREAD

**Issue by Hidden999** [dr3ams/Life-in-the-village-3#78]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.2

### Describe your issue

Just like the title.

Tried to start modpack through curseforge. Get the mincraft menu but when clicking launch it give the game crashed message. 

Never succeeded in starting up the modpack. Couldnt get it to work. 

### Steps to reproduce the issue

1. Click play in curseforge
2. Click play in minecraft launcher
3. Game Crashed Message pops-up 

### Additional Information

[Crash report.txt](https://github.com/dr3ams/Life-in-the-village-3/files/12747959/Crash.report.txt)

**Comment by DoctorMage** [comment]
java crash

did you make any changes to default mojang launcher like moving its install location or anything?

are all launchers stored on internal storage devices

**Comment by Linguardium** [comment]
Looks like an AMD/ATI driver issue when Forge tries to pop up the window. my first suggestion is to check for driver updates. my second suggestion is try disabling oculus and the 3 rubidium mods. sodium (rubidium upstream) and iris (oculus upstream) are known to have some issues with some driver versions. Previously folks have had to update/downgrade their drivers for nvidia, for example

**Comment by Linguardium** [comment]
> when you say older version do oyu mean 1.13? or 2.1?
> 
> also pc specs cpu gpu total ram

Cpu and ram are under the Host section of the crashlog. 

Host: AMD Ryzen 9 5900HX with Radeon Graphics        , 16 cores, 31G,  Windows 11 , 64 bit Build 22621 (10.0.22621.2215)

But you get more info from the SYSTEM section 

---------------  S Y S T E M  ---------------

OS:
 Windows 11 , 64 bit Build 22621 (10.0.22621.2215)
OS uptime: 0 days 20:18 hours

CPU: total 16 (initial active 16) (16 cores per cpu, 2 threads per core) family 25 model 80 stepping 0 microcode 0x0, cx8, cmov, fxsr, ht, mmx, 3dnowpref, sse, sse2, sse3, ssse3, sse4a, sse4.1, sse4.2, popcnt, lzcnt, tsc, tscinvbit, avx, avx2, aes, erms, clmul, bmi1, bmi2, adx, sha, fma, vzeroupper, clflush, clflushopt
Processor Information for all 16 processors :
  Max Mhz: 3301, Current Mhz: 3301, Mhz Limit: 3301

Memory: 4k page, system-wide physical 32118M (19697M free)
TotalPageFile size 36982M (AvailPageFile size 20243M)
current process WorkingSet (physical memory assigned to process): 1356M, peak: 1380M
current process commit charge ("private bytes"): 1436M, peak: 1443M

vm_info: OpenJDK 64-Bit Server VM (17.0.8+7-LTS) for windows-amd64 JRE (17.0.8+7-LTS), built on Jul  7 2023 17:21:55 by "MicrosoftCorporation" with MS VC++ 16.10 / 16.11 (VS2019)
