### ISSUE TITLE
[Bug]: Warp Plates and Share Stones marked as coin reward but unobtainable

### ISSUE THREAD

**Issue by Linguardium** [dr3ams/Life-in-the-village-3#79]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

PrismLauncher

### Modpack version

2.2

### Describe your issue

Warp plates are marked as obtainable via coins in the shop quests https://github.com/dr3ams/Life-in-the-village-3/blob/1b7a71087473eea126bb37914a058db992029a70/kubejs/client_scripts/script.js#L29

Share Stones are also marked as obtainable via coins in the shop quests https://github.com/dr3ams/Life-in-the-village-3/blob/1b7a71087473eea126bb37914a058db992029a70/kubejs/client_scripts/script.js#L25

Neither of these items show up in the rewards snbt for the quests, nor actually in game.

### Steps to reproduce the issue

open files. read them.

open JEI, read descriptions, open FTBQuests and note the discrepancy 

### Additional Information

There is no additional information needed. The information provided, and links, should enough for the pack devs to resolve the issue.

**Comment by dr3ams** [comment]
Added!
