### ISSUE TITLE
[Bug]: Nether's Delight and Phantasmic both replace hoglin loot table

### ISSUE THREAD

**Issue by Linguardium** [dr3ams/Life-in-the-village-3#80]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

PrismLauncher

### Modpack version

2.2

### Describe your issue

Both NourishedNether/Phantasmic and Nether's Delight replace the hoglin loot table instead of using loot modifiers. This leads to load order incompatibilities. If Phantasmic replaces the loot table (higher priority in load order) then you can no longer obtain hoglin loin and complete the quests requiring it.  If Nether's Delight has higher load priority, then you cannot obtain raw hoglin or complete the quests requiring it.

The easy, partial fix for the pack dev is to make a tag for hoglin meat and add both to it, then replace the recipes for the foods using to use this tag. super easy with the existing kubejs stuff. A better option may be to add LootJS to the pack and remove the entire loot table and build a custom one that can handle both outputs.

### Steps to reproduce the issue

open game, generate drops from hoglin loot table

### Additional Information

no additional information necessary.

**Comment by Linguardium** [comment]
The way I resolved this on my side was to make a script adding both hides to a common tag and using a recipe replacement script to set the tag as the input instead of individual hides.  I also added a recipe to the cutting board to turn loin into raw hoglin. I then completely replaced the hoglin loot table with the nether's delight one, so that the output was deterministic.

I am not saying this is the correct method, but it seems to work

**Comment by dr3ams** [comment]
> The way I resolved this on my side was to make a script adding both hides to a common tag and using a recipe replacement script to set the tag as the input instead of individual hides. I also added a recipe to the cutting board to turn loin into raw hoglin. I then completely replaced the hoglin loot table with the nether's delight one, so that the output was deterministic.
> 
> I am not saying this is the correct method, but it seems to work

Your method seems like an option. Can you provide your files so I avoid double work and can include it in the next update?

**Comment by Linguardium** [comment]
[NN_ND_COMPAT.zip](https://github.com/dr3ams/Life-in-the-village-3/files/12802094/NN_ND_COMPAT.zip)

I would suggest testing the changes, of course, to be sure it doesnt do something weird like break loot tables (since that paxi datapack was breaking things completely unrelated to the files in the pack), but i havent noticed issues

**Comment by dr3ams** [comment]
Just tested and it works, thanks!

![image](https://github.com/dr3ams/Life-in-the-village-3/assets/7347489/241d616b-4c0a-41ee-bc7a-f9cdbb49d2d8)
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/7347489/8908d3be-0318-492b-aa4b-b670d043c91a)
