### ISSUE TITLE
[Bug]: Disabling Blossom trees in worldgen removes recipes

### ISSUE THREAD

**Issue by Linguardium** [dr3ams/Life-in-the-village-3#81]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

PrismLauncher

### Modpack version

2/2

### Describe your issue

Title. 

If generation of blossom trees is disabled in quark config https://github.com/dr3ams/Life-in-the-village-3/blob/1b7a71087473eea126bb37914a058db992029a70/config/quark-common.toml#L787 then the recipes for the blossom trees are removed by quark. 

This creates an issue where Blossom logs, planks, etc do not show up in JEI, and planks cannot be crafted without some Create-ive mod usage.  

### Steps to reproduce the issue

open world
look for Blossom things in jei

/give blossom logs and saplings to player since they do not show up
verify you cannot make planks in a crafting table

### Additional Information

I tried "fixing" this by setting a blacklist of "minecraft:is_overworld" for the spawn biome tags and enabling blossom worldgen. This seems to resolve the issue but may cause problems if any mod adds biomes to the overworld and not to the is_overworld biome tag (easily fixed by either adding them to the tag via kubejs or adding them to the blacklist biome list.

**Comment by dr3ams** [comment]
Re-enabled with reduced rarity
