### ISSUE TITLE
[Bug]: can't enter my world when i go to my server

### ISSUE THREAD

**Issue by etoilio** [dr3ams/Life-in-the-village-3#83]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Tlauncher

### Modpack version

1.19.2

### Describe your issue

First i downloaded the modpack on my aternos server, then on curseforge to have it on Tlaucher, and then changed the version of some mods so they are the same on the two sides. When i tried to open my world, it said "Unknown config field:$.auto equip unpacked cards"
can someone help me pls ?

### Steps to reproduce the issue

1 : open Tlauncher with the modpack
2 : open your aternos server and go on it 
3 : the world says "loading terrain" and then an error message 

### Additional Information

when i load a world alone, not on my server, it works without any problem
![but report life in the village on server](https://github.com/dr3ams/Life-in-the-village-3/assets/146999055/a98d6af5-bc87-446a-9f6f-62a8b2b049d1)

**Comment by Linguardium** [comment]
Make sure you are on the same version as your server. This config value was added in 2.2

**Comment by Linguardium** [comment]
remove TLauncher. see if the issue persists with the CurseForge Launcher. TLauncher is piracy which violates the laws in the places this is developed and the places GitHub is hosted.

**Comment by etoilio** [comment]
so you mean i need to buy minecraft ?

**Comment by Linguardium** [comment]
yes, that is how you legally play minecraft...

**Comment by etoilio** [comment]
i guess i'll search help somewhere else
