### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LuxOfCrownGuard** [dr3ams/Life-in-the-village-3#87]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

2.3

### Describe your issue

can't harvest cradling flower from enlightend mod for cerulean vines quest breaking it with hand mining with silk touch and shears fails to make it drop i cant bonemeal it to try and make more and it doesn't show a harvesting tool when i hover it i can't find any info on how to harvest it or if there is a special way to harvest it doesn't say anything about it in quest im not sure if its a bug or if im doing something wrong

### Steps to reproduce the issue

go to end find the enderneath try and harvest cradling flower for quest 

### Additional Information

  https://imgur.com/2xFlKL0
![2023-10-21_09 14 27](https://github.com/dr3ams/Life-in-the-village-3/assets/44307548/34170b1b-8eaf-42f8-83b0-940af207d221)

**Comment by Linguardium** [comment]
Only method i found to harvest it is by abusing endermen pickup (killing an enderman that has picked up one of them will drop what they are holding)

**Comment by dr3ams** [comment]
mod removed
