### ISSUE TITLE
[Bug]: Broken world generation (again)

### ISSUE THREAD

**Issue by romaust** [dr3ams/Life-in-the-village-3#89]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

MultiMC

### Modpack version

2.4

### Describe your issue

Broken world generation in Large Biome world type. Enabling large biomes in a tectonic configuration doesn't help.

### Steps to reproduce the issue

1. Create a world with the "Large Biome" world type
2. Wait until the plot is generated
3. Leave the world and start it again
4. Move towards ungenerated terrain

### Additional Information

[Screenshot](https://imgur.com/a/0pOyexM)
[latest.log](https://gist.github.com/romaust/e5326ec3da95ce913186aa4da1bd2ece)
[debug.log](https://gist.github.com/romaust/8a396cc847da7f248cbe473467fc850e)

**Comment by dr3ams** [comment]
If you want to use Large Biomes world type with Tectonic you need to manually update Tectonic mod and recreate the world.
For now I don't have plans to update this mod because it will brake existing worlds.
