### ISSUE TITLE
[Suggestion]: Replace ViesCraft machines

### ISSUE THREAD

**Issue by manscm** [dr3ams/Life-in-the-village-3#95]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

with this mod: https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft
it has a better feeling of handling the vehicle, upgrade slots, and pretty models overall

**Comment by dr3ams** [comment]
Yep, this is planned
