### ISSUE TITLE
[Bug]: UUID of added entity already exists: BetterFallingBlock

### ISSUE THREAD

**Issue by JokerZB** [dr3ams/Life-in-the-village-3#96]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.6

### Describe your issue

Whenever someone chops down a tree, the console gets spammed with duplicate UUID messages.

`[22:39:34] [Server thread/WARN] [minecraft/PersistentEntitySectionManager]: UUID of added entity already exists: BetterFallingBlock['Falling Block'/168090, l='ServerLevel[world]', x=-134.50, y=104.00, z=1246.50]`

I have searched online for this warning but the posts i find are about single entities with single coordinates. This is neither...

### Additional Information

This happens consistently on own multiplayer server.
Server is Oracle cloud free tier (4 OCPU cores, 24 GB RAM).
Running Pterodactyl server management.

**Comment by Linguardium** [comment]
you may want to add https://modrinth.com/mod/log-begone to prevent those messages. they arent important and can safely be hidden

**Comment by dr3ams** [comment]
> you may want to add https://modrinth.com/mod/log-begone to prevent those messages. they arent important and can safely be hidden

will be added in the next version
