### ISSUE TITLE
[Suggestion]: Revise FTB Ultimine quest to reflect actual usage

### ISSUE THREAD

**Issue by Linguardium** [dr3ams/Life-in-the-village-3#97]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

The current quest text for the FTB Ultimine quest mentions mining tunnels and 3x3 tunnels and such. since the pack disables stone mining with ultimine, these modes are mostly useless and suggesting them may lead to confusion from players who find that they cant actually do what it suggests.

**Comment by cambakr** [comment]
This appears to be a silent change made in 2.3. Some hosts may want to let players Ultimine harvest stone and some of the other blacklisted blocks. The file that handles this is [excluded_blocks.json](https://github.com/dr3ams/Life-in-the-village-3/blob/4b08d4b/config/paxi/datapacks/litv3datapack/data/ftbultimine/tags/blocks/excluded_blocks.json). 

Located at this path: 
`.\config\paxi\datapacks\litv3datapack\data\ftbultimine\tags\blocks\excluded_blocks.json`

Thanks to [/u/LucieTwi on Reddit](https://old.reddit.com/r/feedthebeast/comments/ynb1se/ftb_ultimine/kbumw3a/).
