### ISSUE TITLE
[Bug]: Modpack crushing on death

### ISSUE THREAD

**Issue by makcio6** [dr3ams/Life-in-the-village-3#98]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.6

### Describe your issue

I was playing on a server with this modpack with my friend, and I'm not sure, but maybe after updating the modpack the first time each of us died, the server crashed and we had no way to get our items back since the Corail Tombstone didn't create a grave and the key to it. 
After I died, I decided to intentionally die with an empty inventory, and everything was fine. In single player, exactly the same thing happens. I don't have the slightest idea why this error occurs. I am attaching three crash reports, two of which are from the server, and last one from a singleplayer.
I can’t attach the actual latest.log, since I already launched the game after that.

### Additional Information

[crash-2024-02-04_16.41.27-server.txt](https://github.com/dr3ams/Life-in-the-village-3/files/14319996/crash-2024-02-04_16.41.27-server.txt)
[crash-2024-02-15_18.58.26-server.txt](https://github.com/dr3ams/Life-in-the-village-3/files/14319997/crash-2024-02-15_18.58.26-server.txt)
[crash-2024-02-17_20.50.15-server.txt](https://github.com/dr3ams/Life-in-the-village-3/files/14319998/crash-2024-02-17_20.50.15-server.txt)

**Comment by DoctorMage** [comment]
wanderingTraderRecoveryEnabled and enableFlavorText to false in \config\vtweaks-common.toml
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/df0497c5-4c4f-4af6-8934-adc12b332d80)
